# Generated by Django 4.2.4 on 2023-09-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seqtactic", models.CharField(default="", max_length=2000)),
                ("iduser", models.CharField(default="", max_length=50)),
                ("seqtec", models.CharField(default="", max_length=2000)),
                ("software", models.CharField(default="", max_length=70)),
                ("score", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=70)),
                ("description", models.CharField(default="", max_length=2000)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
    ]
